import Navbar from "./Navbar";
import Link from "next/link";

export const metadata = {
  title: "My First Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            flexBasis: "40%",
            backgroundColor: "#202020",
            color: "#fff",
            padding: "1rem 0",
            marginBottom: "1rem",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <div>
            <h1>
              <Link href={"/"}>Next App</Link>
            </h1>
          </div>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
